### ISSUE TITLE
Internal / external pre- and postprocessing

### ISSUE THREAD

**Issue by pmeier** [pmeier/pystiche_papers#153]
Since all papers we implemented so far use a VGG net with caffe weights as encoder, pre- and postprocessing is necessary. IIRC this isn't mentioned in any paper. 

Right now we assume that the authors are using an internal preprocessing, i. e. as a first step within the encoder. This is not the normal course of action. Although this might be beneficial at runtime, we should consider using the external processing as default.

Cc @jbueltemeier

**Comment by jbueltemeier** [comment]
The pre- and postprocessing is necessary because of the VGG net with caffe weights used and was not introduced by the authors, but only integrated into the implementation because of the necessity. For this reason, I think it would make sense to completely do without the external preprocessing and use only the internal one?

This does not change anything in the original implementation, but only benefits from the internal preprocessing given by the repository of `pystiche`.

What do you think of my thoughts?

**Comment by pmeier** [comment]
Never mind. My main assumption is wrong.
