### ISSUE TITLE
Expose most functions and classes of the reference implementations

### ISSUE THREAD

**Issue by pmeier** [pmeier/pystiche_papers#57]
Currently only few functions for each reference implementation are directly exposed:

https://github.com/pmeier/pystiche_papers/blob/5edfd80d12a038a0ef663f992aa3fc8e87ed8d2c/pystiche_papers/gatys_ecker_bethge_2015/core.py#L18-L22

This can result in requiring multiple imports for no apparent reason:

https://github.com/pmeier/pystiche_papers/blob/5edfd80d12a038a0ef663f992aa3fc8e87ed8d2c/tests/gatys_ecker_bethge_2015/test_core.py#L8-L9

I think we should simply expose everything that is already name-spaced, i.e. prefixed by `author1_author_2_year` or `Author1Author2Year`.

Cc @jbueltemeier

**Comment by jbueltemeier** [comment]
I find the current variant better, because there only the reference implementation is directly exposed, to which it makes sense to call from outside or make changes:
`gatys_ecker_bethge_2015_images`: to use own images
`gatys_ecker_bethge_2015_perceptual_loss`: to change the weights
`gatys_ecker_bethge_2015_nst`: to use the nst from the paper

Whereas all other functions change the actual implementation. To stay with the example with:
`from pystiche_papers.gatys_ecker_bethge_2015 import utils` 

In what case does it make sense to change something in `utils`? It would change the implementation of the paper, if you change the optimizer there to an `Adam` optimizer. And this is something that should be done consciously, for example like here an additional import.

So the current version has two advantages in my opinion:

1. All relevant functions for the use of the implementation of the paper can be used with one import.
2. All others, which change the actual implementation, must be imported explicitly and consciously in addition.

What do you think of my thinking on this?

**Comment by pmeier** [comment]
> In what case does it make sense to change something in utils?

The idea is not that I necessarily want to change something about it, but rather I want to access it more easily. Consider a case where I propose a novel  style loss and want to compare it to the works of Gatys, Ecker, Bethge in 2015. Sure, `gatys_ecker_bethge_2015_nst` is the way to go for their implementation, but to test mine I need their content loss. This is currently not accessible at the top level. Furthermore, I want their optimizer as well as pre- and post-processor.

> And this is something that should be done consciously, for example like here an additional import.

Not sure if I got you right, but this is conscious, isn't it?

```python
from pystiche_papers.gatys_ecker_bethge_2015 import nst, content_loss, optimizer, preprocessor, postprocessor
```

**Comment by jbueltemeier** [comment]
Okay, you're absolutely right. I didn't think of individual components being used in a comparison in my own implementation. Then it makes sense to simply expose everything that is already name-spaced.
