### ISSUE TITLE
Exclude texture synthesis from package scope

### ISSUE THREAD

**Issue by pmeier** [pmeier/pystiche_papers#87]
Currently we switch between NST and texture synthesis (TS) with the `stylization` flag for the Ulyanov et al. paper. Although the implementation is quite similar, the input is different. This leads to bugs (#20) with quirky workarounds. 

On one hand we could have two separate models (`transformer` and `synthesizer`) for both use cases, which would make the interface cleaner. On the other hand I'm considering to remove the TS capability all together, since `pystiche_papers` was created to replicate NST papers.

I'm open for a discussion about this. Cc @jbueltemeier

**Comment by jbueltemeier** [comment]
I would think that this functionality can be removed because, as you said, `pystiche_papers` was created for replication of NST papers and not for TS. It would only be a nice additional functionality with which you could show that TS can also be performed with the `pystiche` framework. However, since you don’t expect this additional functionality and this function requires an extra effort, I don’t see a reason to put more time in it to run it without bugs.

**Comment by pmeier** [comment]
I'll take it up if we have sufficient coverage for the NST part.
